site_name: BlueRockTEL API
site_url: https://bluerocktel-api.github.io
site_description: BlueRockTEL API documentation
site_author: Cyrille Georgel < cyrille.georgel@bluerocktel.com >
nav:
  - Home: index.md
  - Customers: customers.md
theme:
  name: readthedocs
  custom_dir: override
  plugins:
    - search
    - mkpdfs
